language: python
python:
    - 3.7

sudo: false
dist: xenial
matrix:
    fast_finish: true
env:
    matrix:
        - NUMPY=1.14 SCIPY=1.0 CYTHON=0.27
        - NUMPY=1.15 SCIPY=1.1 CYTHON=0.28
        - NUMPY=1.16 SCIPY=1.2 CYTHON=0.29
addons:
    apt:
        packages:
            - libigraph0v5
            - libigraph0-dev

before_install:
    # current python packages via miniconda
    - export MINICONDA="3"
    - travis_retry wget http://repo.continuum.io/miniconda/Miniconda$MINICONDA-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"; hash -r
    - conda config --set always_yes yes --set changeps1 no
    - travis_retry conda update -q conda
    - conda info -a

install:
    # test environment
    - travis_retry conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
    - source activate test-env
    # https://github.com/conda/conda/issues/1367
    - travis_retry conda install -q virtualenv

    # runtime dependencies
    - travis_retry conda install numpy=$NUMPY scipy=$SCIPY cython=$CYTHON

    # testing dependencies
    - travis_retry conda install -q networkx matplotlib basemap sphinx pytest
    - travis_retry pip   install -q tox pytest-xdist pytest-flake8 pytest-cov pylint codecov

before_script:
    # limit py.test processes within container environment
    - sed 's/auto/2/' pytest.ini > temp && mv temp pytest.ini

script:
    # run test suite in dev env
    - pip install -r requirements.txt -e .
    - tox

    # run cleanup script
    - ./tools/publish 1 0 0 1; export DIST="$(basename `ls ../pyunicorn-*` .tar.gz)"; cd ..; tar xzf $DIST.tar.gz; cd $DIST

    # run test suite in source distribution (without Cython)
    - conda uninstall -q cython
    - python setup.py sdist; cd dist; tar xzf $DIST.tar.gz; cd $DIST
    - tox -e units
    
after_success:
    - codecov

notifications:
    email:
        on_success: change
        on_failure: always
